services:
  cert-manager:
    build: .
    image: ghcr.io/hpware/caddy-and-cert-manager
    ports:
      - "3000:3000"
    environment:
      DATABASE_URL: postgresql://${DB_USER}:${DB_PASSWORD}@postgres:5432/cert_db
      NEXT_PUBLIC_URL: ${NEXT_PUBLIC_URL}
      NEXT_PUBLIC_GUEST_RESOURCES_HOST: ${NEXT_PUBLIC_GUEST_RESOURCES_HOST}
      NEXT_PUBLIC_GUEST_RESOURCES_URL: ${NEXT_PUBLIC_GUEST_RESOURCES_URL}
      NEXT_PUBLIC_SSO_ENABLE: ${NEXT_PUBLIC_SSO_ENABLE}
      SSO_CLIENT_ID: ${SSO_CLIENT_ID}
      SSO_CLIENT_SECRET: ${SSO_CLIENT_SECRET}
      SSO_DISCOVERY_URL: ${SSO_DISCOVERY_URL}
      IGNORE_PROTECTIONS: ${IGNORE_PROTECTIONS}
      PROTECTION_PROXY_URL: ${PROTECTION_PROXY_URL}
      PROTECTION_PROXY_TOKEN: ${PROTECTION_PROXY_TOKEN}
    depends_on:
      - postgres
      - porca
    volumes:
      - ./certs/ca:/app/certs/created
      - ./certs/master.pub.pem:/app/certs/master.pub.pem
  porca:
    build: ./porca
    image: ghcr.io/hpware/cert-porca
    # Do NOT open ports on this program, this should be a secure layer for the critial certificates.
    volumes:
      - ./certs:/app/certs
    environment:
      IGNORE_PROTECTIONS: ${IGNORE_PROTECTIONS}
      PROTECTION_PROXY_URL: ${PROTECTION_PROXY_URL}
      PROTECTION_PROXY_TOKEN: ${PROTECTION_PROXY_TOKEN}
      NEXT_PUBLIC_GUEST_RESOURCES_URL: ${NEXT_PUBLIC_GUEST_RESOURCES_URL}
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:4000/ok"]
      interval: 30s
      timeout: 5s
      retries: 3
      start_period: 15s
  postgres:
    image: postgres:16-alpine
    restart: unless-stopped
    environment:
      POSTGRES_DB: cert_db
      POSTGRES_USER: ${DB_USER}
      POSTGRES_PASSWORD: ${DB_PASSWORD}
    ports:
      - "5432:5432"
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U $$POSTGRES_USER -d cert_db"]
      interval: 10s
      timeout: 5s
      retries: 5
    volumes:
      - postgres-data:/var/lib/postgresql/data

volumes:
  postgres-data:
