# these two are required.
ORG_NAME="Default CA generated by CS"
CN_NAME="Default CA generated by CS"

# create cert
mkdir -p /certs/created
openssl genrsa -out ./certs/master.key.pem 4096
openssl req -x509 -new -nodes -key ./certs/master.key.pem -sha512 -days 7305 -out ./certs/master.pub.pem -subj "/C=TW/L=Taipei/O=${ORG_NAME}/CN=${CN_NAME}"

# generate default cert for the default HTTPS port.
openssl genrsa -out ./certs/created/default.private_key.pem 4096
openssl req -new -key ./certs/created/default.private_key.pem -out ./certs/created/default.csr.pem -subj "/C=TW/L=Taipei/O=${ORG_NAME}/CN=test.default.tw"
openssl x509 -req -in ./certs/created/default.csr.pem -CA ./certs/master.pub.pem -CAkey ./certs/master.key.pem -CAcreateserial -out ./certs/created/default.pub.pem -days 7305 -sha512
cat ./certs/created/default.pub.pem ./certs/master.pub.pem > ./certs/default.fullchain.pem

# create Caddyfile
mkdir -p caddy/conf
tee ./caddy/conf/Caddyfile <<EOF
:80 {
        root * /usr/share/caddy
        file_server
}
:443 {
        tls /certs/default.fullchain.pem /certs/default.private_key.pem
        root * /usr/share/caddy
        file_server
}
EOF
